"""Updated parents model

Revision ID: 899950243b3d
Revises: afb7860c4694
Create Date: 2024-01-28 14:18:25.264277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899950243b3d'
down_revision: Union[str, None] = 'afb7860c4694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'parents', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parents', type_='unique')
    op.drop_column('parents', 'password')
    # ### end Alembic commands ###
