"""initial

Revision ID: afb7860c4694
Revises: 
Create Date: 2024-01-26 08:22:00.393612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import UniqueConstraint  # Import the UniqueConstraint module

# revision identifiers, used by Alembic.
revision: str = 'afb7860c4694'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(length=25), nullable=False),
        sa.Column('last_name', sa.String(length=25), nullable=False),
        sa.Column('gender', sa.String(), nullable=False),
        sa.Column('phone_number', sa.String(length=25), nullable=False),
        sa.Column('email', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('teachers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(length=25), nullable=False),
        sa.Column('last_name', sa.String(length=25), nullable=False),
        sa.Column('gender', sa.String(), nullable=False),
        sa.Column('phone_number', sa.String(length=25), nullable=False),
        sa.Column('email', sa.String(length=50), nullable=False),
        sa.Column('role', sa.String(length=25), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('classes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=25), nullable=False),
        sa.Column('teacher_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        UniqueConstraint('name', name='uq_classes_name'),  # Add a unique constraint
        sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='fk_classes_teacher_id'),  # Add ForeignKeyConstraint name
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('students',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(length=25), nullable=False),
        sa.Column('last_name', sa.String(length=25), nullable=False),
        sa.Column('gender', sa.String(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=False),
        sa.Column('class_name', sa.String(length=25), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['class_name'], ['classes.name'], name='fk_students_class_name'),  # Add ForeignKeyConstraint name
        sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], name='fk_students_parent_id'),  # Add ForeignKeyConstraint name
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('grades',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=True),
        sa.Column('mathematics', sa.Integer(), nullable=False),
        sa.Column('english', sa.Integer(), nullable=False),
        sa.Column('science', sa.Integer(), nullable=False),
        sa.Column('kiswahili', sa.Integer(), nullable=False),
        sa.Column('social_studies', sa.Integer(), nullable=False),
        sa.Column('religious_education', sa.Integer(), nullable=False),
        sa.Column('total', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_grades_student_id'),  # Add ForeignKeyConstraint name
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    op.drop_table('students')
    op.drop_table('classes')
    op.drop_table('teachers')
    op.drop_table('parents')
    # ### end Alembic commands ###
